databases:
  - name: emma
    plan: free
    databaseName: emma
    user: postgres

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"

    startCommand: "python -m waitress --port=$PORT newspaper.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emma
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
